### ISSUE TITLE
test_driver_2.py fails

### ISSUE THREAD

**Issue by alexanderplatz1999** [alexanderplatz1999/tega#28]
deepcopy_() function does not work for a cont object including RPC:
```
INFO:2015-07-23 03:50:38,678:Reloading done
Traceback (most recent call last):
  File "/root/tega/tests/tega/servers/server", line 6, in <module>
    main()
  File "/root/tega/tega/server.py", line 682, in main
    singleton.initialize()
  File "/root/tega/plugins/local1/plugins/plugin.py", line 24, in initialize
    t.put(a.x)
  File "/root/tega/tega/idb.py", line 488, in put
    qname = instance.qname_()
AttributeError: 'NoneType' object has no attribute 'qname_'
```

**Comment by alexanderplatz1999** [comment]
Fixed: commit d70d7b6ddfb96a6c6e516c9a8f82bef890ff2d30
