### ISSUE TITLE
qname2path fails with integer keys

### ISSUE THREAD

**Issue by alexanderplatz1999** [alexanderplatz1999/tega#30]
```
Python 3.4.3 (default, Mar 20 2015, 21:07:59)
[GCC 4.7.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tega.util import qname2path
>>> qname2path(['r', 'a', 100])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/tega/tega/util.py", line 51, in qname2path
    return ('.').join(qname_)
TypeError: sequence item 2: expected str instance, int found
>>>
```

**Comment by alexanderplatz1999** [comment]
Fixed: commit 50957b111d900a9f7812e9288c1f388c468fa420
